%%
%% This is file `YNUthesis.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% YNUthesis.dtx  (with options: `class')
%% 
%% Copyright (C) 2023 by Rui-Zhi Li <liruizhi0871@gmail.com>
%% ---------------------------------------------------------------------
%% 
%% This work may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License, either
%% version 1.3c of this license or (at your option) any later
%% version. This version of this license is in
%%    http://www.latex-project.org/lppl/lppl-1-3c.txt
%% and the latest version of this license is in
%%    http://www.latex-project.org/lppl.txt
%% and version 1.3 or later is part of all distributions of
%% LaTeX version 2005/12/01 or later.
%% 
%% This work has the LPPL maintenance status "maintained".
%% 
%% The Current Maintainer of this work is Rui-Zhi Li.
%% 
%% This work consists of the files YNUthesis.dtx,
%%           and the derived files YNUthesis.ins,
%%                                 YNUthesis.cls,
%%                             and README.md.
%% ---------------------------------------------------------------------
%% 
\NeedsTeXFormat{LaTeX2e}[2020/01/01]
\ProvidesClass{YNUthesis}
\endinput
%%
%% End of file `YNUthesis.cls'.
