name: Compiling LaTeX template

on:
  push:
    branches:
      - 'main'
    path:
      - ['**.dtx','**.tex']

jobs:
  Thesis_Template:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/texlive-action/small@v1
      with:
        run: |
          xetex YNUthesis.dtx
    
    - name: Make Artifact
      run: |
        mkdir template
        cp main.tex template/
        cp main.bib template/
        cp YNUlogo.sty template/
        cp YNUthesis.cls template/
        cp YNUthesis.def template/
        cp latexmkrc template/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: YNU thesis template
        path: template